### ISSUE TITLE
GHC-8.4.x support (in Hackage)

### ISSUE THREAD

**Issue by yairchu** [JonasDuregard/testing-feat#7]
The `master` branch already supports GHC-8.4.x but these changes weren't uploaded to hackage.
It would be nice to be able to use aeson-diff in cabal-based builds or in stack-based builds without extra `stack.yaml` chants :)

**Comment by JonasDuregard** [comment]
Uploaded version 1.0 to hackage.

**Comment by yairchu** [comment]
Hmm, it looks like hackage doesn't have the same code as GitHub, for example in
https://hackage.haskell.org/package/testing-feat-1.0.0.0/docs/src/Test.Feat.Enumerate.html
(Which I get when going to https://hackage.haskell.org/package/testing-feat, clicking on the Enumerate module and clicking "source")
there is no mention of `Semigroup`, in constrast to the [version on GitHub](https://github.com/JonasDuregard/testing-feat/blob/master/Test/Feat/Enumerate.hs)..
